
---
- name: Create VMs in vCenter
  hosts: all
  gather_facts: no
  tasks:
    - name: Create VM
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        folder: "{{ folder }}"
        template: "{{ template_name }}"
        name: "{{ inventory_hostname }}"
        networks:
          - name: "{{ network_name }}"
            ip: "{{ ip }}"
            netmask: "{{ netmask }}"
            gateway: "{{ gateway }}"
            domain: "{{ domain }}"
        state: poweredon
